### ISSUE TITLE
Some practical questions

### ISSUE THREAD

**Issue by cyberjunky** [eppenga/Sunflow-Cryptobot#3] opened 2024-04-22 20:00 UTC
Did you back test to select best symbols and optimize/find good settings somehow?
I consider running USDC symbols instead of USDT (only the ones with biggest daily volume) since they don't have trading fees.
But didn't look into detail yet.

**Comment by eppenga** [comment] 2024-04-23 09:57
Nope, no backtesting here. I have an opinion on backtesting which I gladly share sometime, but to keep it short, I prefer to develop mathematical / statistical methods which work regardless of backtesting. Running without trading fees for this bot could be profitable as it can do high frequency trades, almost like scalping. Volume might be an issue, especially because it sets market orders which are influenced much harder by lower volumes, but let's try! Could you give me maybe a few example of these USDC pairs?

**Comment by cyberjunky** [comment] 2024-04-23 10:55
The obvious ones are BTCUSDC, ETHUSDC, XRPUSDC, DOGEUSDC, SOLUSDC, AVAXUSDC have some volume, they seem to work with SunFlow, it tries to buy, but I have no funds yet. Your approach is unique.. we should chat at the office some time. ;-)

**Comment by eppenga** [comment] 2024-04-23 17:56
Just setup a test on AVAXUSDC, all seems to run fine. Wasn't aware that it's really without fees, thx! Double checking API response and indeed it says CumExecFee equals 0 :) 

BTW also changed some things again, you might need to do a pull request, pls. be aware the config.py files is changed, did this to allow it run multiple instances of the same symbol via different sub accounts. Want to use that for testing what's the best way to calculate trigger distance.

**Comment by eppenga** [comment] 2024-04-28 21:28
@cyberjunky > Did some overhauling this weekend, not as much as I wanted, mainly improved trigger price distance calculations, fixed some bugs and optimized. Also professionalized releasing a bit, have a development environment now, a test and a production. For the test environment I setup three sub accounts that run all the same symbols, so they are comparable and can see which settings work best.

![image](https://github.com/eppenga/Sunflow-Cryptobot/assets/4440994/64b0602b-6c20-42b6-8972-38985c0444e6)
Kline buy prevention is now also working as intended, yay! Ok...it made one failure :)

Will make a wish list of all the featured had in mind, also ran the first (non successful lol :)) tests with LSTM and ARIMA models for price predictions. Python has so much cool things to offer, never knew this :)

**Comment by cyberjunky** [comment] 2024-04-29 07:14
@eppenga wow nice, I will try it! Python is still the number one programming language for a reason!
I noted myself to add [Apprise ](https://github.com/caronc/apprise)to your script/logging, so you can notify Buy/Sell moments via Telegram, e-mail etc. etc.
Only a few lines of code are needed.  For AI I have this one bookmarked (amoung others): [Trading predictions using AI and Python](https://eodhd.medium.com/trading-predictions-using-ai-and-python-cdaad4de3447)

**Comment by eppenga** [comment] 2024-04-29 07:46
Thanks so much! Valuable info!!

**Comment by eppenga** [comment] 2024-04-30 19:39
> @eppenga wow nice, I will try it! Python is still the number one programming language for a reason! I noted myself to add [Apprise ](https://github.com/caronc/apprise)to your script/logging, so you can notify Buy/Sell moments via Telegram, e-mail etc. etc. Only a few lines of code are needed. For AI I have this one bookmarked (amoung others): [Trading predictions using AI and Python](https://eodhd.medium.com/trading-predictions-using-ai-and-python-cdaad4de3447)

Only intended to make live easy and please do not feel obligated to add Telegram at all, here are the hooks that you could use:

_Bought or Sold, please see trailing.py starting line 96:_
> 
        # Check if trailing order if filled, if so reset counters and close trailing process
        if order['result']['list'] == []:
            print(defs.now_utc()[1] + "Trailing: check_order: Trailing " + active_order['side'] + ": *** Order has been filled! ***\n")


_Going to Buy, please see sunflow.py starting line 358, when can_buy flips to True:_
>
        # Get buy decission and report
        result  = defs.decide_buy(indicators_advice, use_indicators, spread_advice, use_spread, orderbook_advice, use_orderbook, interval, intervals)
        can_buy = result[0]
        message = result[1]
        print(defs.now_utc()[1] + "Sunflow: buy_matrix: " + message + "\n")

_Going to Sell, please see sunflow.py starting line 183, when can_sell flips to True:_
>
            # Check if and how much we can sell
            result                  = orders.check_sell(new_spot, profit, active_order, all_buys, info)
            all_sells_new           = result[0]
            active_order['qty_new'] = result[1]
            can_sell                = result[2]
            rise_to                 = result[3]

**Comment by cyberjunky** [comment] 2024-05-01 11:10
It's a start, more info like price, amounts of buy/sells, wallet size, and realized pnl are things I think about.
![image](https://github.com/eppenga/Sunflow-Cryptobot/assets/5447161/6af564d2-1082-45c7-888d-bfe49a21b95c)

**Comment by eppenga** [comment] 2024-05-01 14:26
Wow, almost looks like a professional bot this way! Python is awesome, I think from nothing to this in about a month, with some help from YouTube, Visual Studio (what an awesome editor is that...my fanciest ever was Notepad++), ChatGPT and you. So cool :)

**Comment by cyberjunky** [comment] 2024-05-01 14:38
In my other bot scripts I have added a telegram bot mechanism, so you can ask for info, stop/start bot, panic sell etc from it's Telegram channel... but lets start small ;-)
Visual Studio is awesome indeed, I'm testing with the Github Copilot add-in (and subscription) it even suggest code and naming while typing... and you can ask it to create docstrings etc. etc.

**Comment by eppenga** [comment] 2024-05-01 14:41
Nice nice! I am still old school, create functional designs and things and then start coding ;) Cool stuff!

**Comment by eppenga** [comment] 2024-05-01 18:56
Merged the commit, great fun to see Sunflow outputting to my Telegram. It's a bit talkative, think I will remove some messages later.

**Comment by YogaDarma182** [comment] 2024-05-10 01:34
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
Nerijusvinyl, @mhansinger, @flfsbr, @nidkil, @Crypto-T-Rex, @alexgorbachev, @adrianlorion, @Dennis-Chhun, @oschino, @lookfirst, @ne0c0de, @NoasProject, @lichdb, @RealAUM, @suprnurd, @d-eepen, @JoonyoungYi, @cett01, @abuuuuuuuuuu, @stanlee321, @dorucioclea, @jordimarinvalle, @aumanusorn, @asik03, @jiec-msft, @180808k, @irrenhaus, @fatihtoprak, @moeen, @boutterudy, @wizcap, @thurahtetaung, @Dvorson, @shifting-tides, @gtpedrosa, @sunnyzhifei, @Z-Xiong, @Hudie, @Albermonte, @vietbaoa4htk, @john523, @Bioanalytica, @sarievdima08, @tarmylan, @OmidRafiee, @ruchithak, @tsukumijima, @muratakcs, @mrblackstars, @bizlift

**Comment by eppenga** [comment] 2024-05-15 15:19
Thx for all your feedback @cyberjunky , fyi it has profit calculations now which are also displayed through apprise. Also lots of other bugs have been fixed and it's all much more stable now.

On price predictions I opened up the new ChatGPT version which was released yesterday and wanted to try the API, so I wrote this in literally 10 minutes (Python is awesome) and ok, only tried it 5 minutes, but... I'm amazed, but it might just be luck...

>
    from openai import OpenAI
    import configai, preload, time

    # Get a list of prices
    prices = preload.get_prices("XRPUSDC", 100)

    # Connect to ChatGPT
    client = OpenAI(api_key=configai.api_key)

    # Do logic
    start_time = int(time.time() * 1000)
    completion = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": "You are a fortune teller that can really predict the future."},
        {"role": "user",   "content": "Predict the next price based on this list and only output the number itself."},
        {"role": "user",   "content": "The list contains the time in miliseconds and the price at that moment in time."},
        {"role": "user",   "content": str(prices)}
    ]
    )
    end_time = int(time.time() * 1000)

    # Output to stdout
    predicted_price = completion.choices[0].message
    print(f"ChatGPT predicts {predicted_price} and it took {end_time - start_time}ms")

**Comment by cyberjunky** [comment] 2024-05-16 06:33
@eppenga Nice work, I think you didn't update the repo yet. if done I'm going to try it out soon!
The ChatGPT part looks nice, but I don't have a paid subscription yet, I thinks it's needed.

**Comment by eppenga** [comment] 2024-05-16 07:31
Well I tested it a bit further yesterday night and asking ChatGPT to predict one or two prices in the future is OK-ish, but when you go up to ten, nah... Ohw yes, another thing, it is soooo slow....never seen it give an answer in less than .5 seconds. But, still, it is very interesting to see how the ChatGPT API works and what you can with it. Yes, costs a bit of money, I put in a couple of Euros for the API, it's hardly using it, it's cheap.

**Closed as completed** 2024-05-30 14:26 UTC
